import { createHash, randomBytes, randomUUID } from "node:crypto";
import type { BrainStore } from "./store";
import type { AccessScope } from "./access-tokens";
import type { AutomationPolicy, AgentRunStatus, MutationProposal } from "./autonomous";
import { recordAuditEvent, listAuditEvents, listAuditEventsPage, type AuditEvent, type AuditEventPage } from "./audit";

type Store = Pick<BrainStore, "query" | "transaction">;

export interface ControlPlaneContext { principal: string; tenantId: string; brainId?: string; scope: AccessScope; }
export interface AdminDashboard { tenantId: string; brains: number; users: number; sources: number; activeJobs: number; failedJobs: number; projectionLag: number; activeModels: number; auditEvents: number; }
export interface DurableWebSession { id: string; tenantId: string; userId: string; csrfToken: string; createdAt: string; idleExpiresAt: string; absoluteExpiresAt: string; }
export interface DurableAgentRun { id: string; tenantId: string; brainId: string; agent: string; operation: string; baseCommit: string; authority: AutomationPolicy["authority"]; budget: AutomationPolicy; plannedPaths: string[]; status: AgentRunStatus; proposal?: MutationProposal; result?: { commit?: string; dryRun: boolean; completedAt: string }; error?: string; }
export interface RollbackReceipt { id: string; tenantId: string; brainId: string; runId?: string; targetKind: string; targetId: string; rollbackRef: string; metadata: Record<string, unknown>; createdAt: string; }
export interface SchemaUpgradePlan { id: string; tenantId: string; brainId: string; fromVersion: string; toVersion: string; status: "planned" | "approved" | "applied" | "rolled_back" | "rejected"; changes: Array<{ path: string; from?: string; to: string; byteChange: boolean }>; approval?: { principal: string; at: string }; }
export interface MigrationDrill { id: string; tenantId: string; brainId: string; stage: string; status: "planned" | "running" | "passed" | "failed"; evidence: Record<string, unknown>; createdAt: string; }
export interface DurableGroup { id: string; tenantId: string; name: string; }
export interface DurableVisibilityGrant { id: string; tenantId: string; brainId: string; subjectType: "user" | "group" | "tenant"; subjectId: string; label: string; }

function jsonValue<T>(value: unknown, fallback: T): T { const parsed = typeof value === "string" ? JSON.parse(value) : value; return parsed === undefined || parsed === null ? fallback : parsed as T; }
function requireAdmin(context: ControlPlaneContext): void { if (!context.principal.trim() || !context.tenantId.trim() || context.scope !== "admin") throw new Error("admin scope is required"); }
function hash(value: string): string { return createHash("sha256").update(value).digest("hex"); }

export class DurableControlPlane {
	constructor(private readonly store: Store, private readonly clock: () => Date = () => new Date()) {}
	private async audit(context: ControlPlaneContext, action: string, subjectId?: string, metadata: Record<string, unknown> = {}): Promise<void> { await recordAuditEvent(this.store, { tenantId: context.tenantId, action, subjectId, metadata: { principal: context.principal, ...metadata } }); }

	async createUser(context: ControlPlaneContext, input: { id: string }): Promise<{ id: string }> {
		requireAdmin(context); if (!input.id.trim()) throw new Error("user ID is required");
		const rows = await this.store.query<{ id: string }>("INSERT INTO brain_users (id) VALUES ($1) RETURNING id", [input.id]); await this.audit(context, "admin.user.created", input.id); return { id: rows[0]!.id };
	}
	async createTenant(context: ControlPlaneContext, input: { id: string; name: string; ownerUserId: string }): Promise<{ id: string; name: string }> {
		requireAdmin(context); if (!input.id.trim() || !input.name.trim() || !input.ownerUserId.trim()) throw new Error("tenant fields are required");
		const result = await this.store.transaction(async (transaction) => { const rows = await transaction.query<{ id: string; name: string }>("INSERT INTO brain_tenants (id, name) VALUES ($1, $2) RETURNING id, name", [input.id, input.name]); await transaction.query("INSERT INTO brain_memberships (user_id, tenant_id, role) VALUES ($1, $2, 'owner')", [input.ownerUserId, input.id]); return rows[0]!; }); await this.audit(context, "admin.tenant.created", input.id, { ownerUserId: input.ownerUserId }); return result;
	}
	async createBrain(context: ControlPlaneContext, input: { id: string; name: string; canonicalRemote?: string }): Promise<{ id: string; tenantId: string; name: string; canonicalRemote?: string }> {
		requireAdmin(context); if (!input.id.trim() || !input.name.trim()) throw new Error("brain fields are required");
		const rows = await this.store.query<{ id: string; tenant_id: string; name: string; canonical_remote: string | null }>("INSERT INTO brain_registry (id, tenant_id, name, canonical_remote) VALUES ($1, $2, $3, $4) RETURNING id, tenant_id, name, canonical_remote", [input.id, context.tenantId, input.name, input.canonicalRemote ?? null]); await this.audit(context, "admin.brain.created", input.id, { name: input.name }); const row = rows[0]!; return { id: row.id, tenantId: row.tenant_id, name: row.name, ...(row.canonical_remote ? { canonicalRemote: row.canonical_remote } : {}) };
	}
	async grantMembership(context: ControlPlaneContext, input: { userId: string; brainId?: string; role: "member" | "admin" | "owner"; visibilityLabels?: string[] }): Promise<void> {
		requireAdmin(context); const labels = input.visibilityLabels ?? []; if (!input.userId.trim() || !["member", "admin", "owner"].includes(input.role) || labels.some((label) => !label.trim())) throw new Error("invalid membership");
		if (input.brainId) { const rows = await this.store.query<{ user_id: string }>("INSERT INTO brain_members (user_id, tenant_id, brain_id, role, visibility_labels) SELECT $1, $2, $3, $4, $5::jsonb WHERE EXISTS (SELECT 1 FROM brain_registry WHERE id = $3 AND tenant_id = $2) RETURNING user_id", [input.userId, context.tenantId, input.brainId, input.role, JSON.stringify(labels)]); if (!rows.length) throw new Error("brain is not in the tenant"); } else await this.store.query("INSERT INTO brain_memberships (user_id, tenant_id, role, visibility_labels) VALUES ($1, $2, $3, $4::jsonb)", [input.userId, context.tenantId, input.role, JSON.stringify(labels)]);
		await this.audit(context, "admin.membership.granted", input.userId, { brainId: input.brainId ?? null, role: input.role, visibilityLabels: labels });
	}
	async createGroup(context: ControlPlaneContext, input: { id: string; name: string }): Promise<DurableGroup> {
		requireAdmin(context); if (!input.id.trim() || !input.name.trim()) throw new Error("group fields are required");
		const rows = await this.store.query<{ id: string; tenant_id: string; name: string }>("INSERT INTO brain_groups (id, tenant_id, name) VALUES ($1, $2, $3) RETURNING id, tenant_id, name", [input.id, context.tenantId, input.name]);
		await this.audit(context, "admin.group.created", input.id, { name: input.name });
		return { id: rows[0]!.id, tenantId: rows[0]!.tenant_id, name: rows[0]!.name };
	}
	async addGroupMember(context: ControlPlaneContext, input: { groupId: string; userId: string }): Promise<void> {
		requireAdmin(context); if (!input.groupId.trim() || !input.userId.trim()) throw new Error("group membership fields are required");
		const rows = await this.store.query<{ group_id: string }>("INSERT INTO brain_group_members (group_id, user_id) SELECT $1, $2 WHERE EXISTS (SELECT 1 FROM brain_groups WHERE id = $1 AND tenant_id = $3) AND EXISTS (SELECT 1 FROM brain_users WHERE id = $2) RETURNING group_id", [input.groupId, input.userId, context.tenantId]);
		if (!rows.length) throw new Error("group or user is unavailable");
		await this.audit(context, "admin.group.member-added", input.userId, { groupId: input.groupId });
	}
	async grantVisibility(context: ControlPlaneContext, input: { brainId: string; subjectType: "user" | "group" | "tenant"; subjectId: string; label: string }): Promise<DurableVisibilityGrant> {
		requireAdmin(context); if (!input.brainId.trim() || !input.subjectId.trim() || !input.label.trim() || !["user", "group", "tenant"].includes(input.subjectType)) throw new Error("invalid visibility grant");
		const brain = await this.store.query<{ id: string }>("SELECT id FROM brain_registry WHERE id = $1 AND tenant_id = $2", [input.brainId, context.tenantId]);
		if (!brain.length) throw new Error("brain is unavailable");
		if (input.subjectType === "tenant" && input.subjectId !== context.tenantId) throw new Error("tenant grant is outside the requested tenant");
		const subject = input.subjectType === "user" ? await this.store.query<{ id: string }>("SELECT id FROM brain_users WHERE id = $1", [input.subjectId]) : input.subjectType === "group" ? await this.store.query<{ id: string }>("SELECT id FROM brain_groups WHERE id = $1 AND tenant_id = $2", [input.subjectId, context.tenantId]) : [{ id: context.tenantId }];
		if (!subject.length) throw new Error("visibility subject is unavailable");
		const rows = await this.store.query<{ id: string }>("INSERT INTO brain_visibility_grants (id, tenant_id, brain_id, subject_type, subject_id, label) VALUES ($1, $2, $3, $4, $5, $6) RETURNING id", [randomUUID(), context.tenantId, input.brainId, input.subjectType, input.subjectId, input.label]);
		await this.audit(context, "admin.visibility.granted", rows[0]!.id, { brainId: input.brainId, subjectType: input.subjectType, subjectId: input.subjectId, label: input.label });
		return { id: rows[0]!.id, tenantId: context.tenantId, brainId: input.brainId, subjectType: input.subjectType, subjectId: input.subjectId, label: input.label };
	}
	async registerSource(context: ControlPlaneContext, input: { id: string; brainId: string; version: string; kind: string; compatibility?: Record<string, unknown> }): Promise<void> {
		requireAdmin(context); if (!input.id.trim() || !input.brainId.trim() || !input.version.trim() || !input.kind.trim()) throw new Error("source registration fields are required");
		await this.store.query("INSERT INTO brain_source_registrations (id, tenant_id, brain_id, version, kind, compatibility) VALUES ($1, $2, $3, $4, $5, $6::jsonb) ON CONFLICT (id) DO UPDATE SET version = EXCLUDED.version, kind = EXCLUDED.kind, compatibility = EXCLUDED.compatibility, updated_at = now() WHERE brain_source_registrations.tenant_id = EXCLUDED.tenant_id", [input.id, context.tenantId, input.brainId, input.version, input.kind, JSON.stringify(input.compatibility ?? {})]); await this.audit(context, "admin.source.registered", input.id, { brainId: input.brainId, version: input.version, kind: input.kind });
	}
	async setSourceEnabled(context: ControlPlaneContext, sourceId: string, enabled: boolean): Promise<void> { requireAdmin(context); if (!sourceId.trim()) throw new Error("source ID is required"); const rows = await this.store.query<{ id: string }>("UPDATE brain_source_registrations SET enabled = $3, updated_at = now() WHERE id = $1 AND tenant_id = $2 RETURNING id", [sourceId, context.tenantId, enabled]); if (!rows.length) throw new Error("source is not available"); await this.audit(context, enabled ? "admin.source.enabled" : "admin.source.disabled", sourceId); }
	async listSources(context: ControlPlaneContext, brainId?: string): Promise<Array<Record<string, unknown>>> { if (!context.principal.trim() || !context.tenantId.trim()) throw new Error("tenant scope is required"); const rows = await this.store.query<{ id: string; brain_id: string; version: string; kind: string; enabled: boolean; compatibility: unknown; health: unknown }>("SELECT id, brain_id, version, kind, enabled, compatibility, health FROM brain_source_registrations WHERE tenant_id = $1 AND ($2::text IS NULL OR brain_id = $2) ORDER BY id", [context.tenantId, brainId ?? null]); return rows.map((row) => ({ id: row.id, brainId: row.brain_id, version: row.version, kind: row.kind, enabled: row.enabled, compatibility: jsonValue(row.compatibility, {}), health: jsonValue(row.health, {}) })); }
	async registerOAuthClient(context: ControlPlaneContext, input: { id: string; name: string; redirectUris: string[]; scopes: AccessScope[]; publicClient?: boolean; clientSecret?: string }): Promise<{ id: string }> { requireAdmin(context); if (!input.id.trim() || !input.name.trim() || !input.redirectUris.length || input.redirectUris.some((uri) => !uri.trim() || uri.includes("#")) || !input.scopes.length) throw new Error("invalid OAuth client"); await this.store.query("INSERT INTO brain_oauth_clients (id, tenant_id, name, public_client, redirect_uris, scopes, client_secret_hash) VALUES ($1, $2, $3, $4, $5::jsonb, $6::jsonb, $7)", [input.id, context.tenantId, input.name, input.publicClient ?? true, JSON.stringify(input.redirectUris), JSON.stringify([...new Set(input.scopes)]), input.clientSecret ? hash(input.clientSecret) : null]); await this.audit(context, "admin.oauth-client.created", input.id, { name: input.name, scopes: [...new Set(input.scopes)] }); return { id: input.id }; }
	async revokeOAuthClient(context: ControlPlaneContext, clientId: string): Promise<void> { requireAdmin(context); const rows = await this.store.query<{ id: string }>("UPDATE brain_oauth_clients SET revoked_at = now() WHERE id = $1 AND tenant_id = $2 AND revoked_at IS NULL RETURNING id", [clientId, context.tenantId]); if (!rows.length) throw new Error("OAuth client is unavailable"); await this.audit(context, "admin.oauth-client.revoked", clientId); }
	async createWebSession(context: ControlPlaneContext, userId: string, options: { idleMs?: number; absoluteMs?: number } = {}): Promise<DurableWebSession> { if (!context.principal.trim() || !context.tenantId.trim() || !userId.trim()) throw new Error("invalid session context"); const id = randomBytes(32).toString("base64url"); const csrfToken = randomBytes(32).toString("base64url"); const createdAt = this.clock(); const idleExpiresAt = new Date(createdAt.getTime() + (options.idleMs ?? 30 * 60_000)); const absoluteExpiresAt = new Date(createdAt.getTime() + (options.absoluteMs ?? 8 * 60 * 60_000)); if (idleExpiresAt <= createdAt || absoluteExpiresAt <= createdAt) throw new Error("invalid session lifetime"); await this.store.query("INSERT INTO brain_web_sessions (id, session_hash, tenant_id, user_id, csrf_hash, idle_expires_at, absolute_expires_at) VALUES ($1, $2, $3, $4, $5, $6, $7)", [randomUUID(), hash(id), context.tenantId, userId, hash(csrfToken), idleExpiresAt.toISOString(), absoluteExpiresAt.toISOString()]); return { id, tenantId: context.tenantId, userId, csrfToken, createdAt: createdAt.toISOString(), idleExpiresAt: idleExpiresAt.toISOString(), absoluteExpiresAt: absoluteExpiresAt.toISOString() }; }
	async validateWebSession(context: ControlPlaneContext, sessionId: string, csrfToken: string, stateChanging = false): Promise<DurableWebSession> { if (!sessionId.trim() || !csrfToken.trim()) throw new Error("session credentials are required"); const now = this.clock(); const nowIso = now.toISOString(); const rows = await this.store.query<{ id: string; tenant_id: string; user_id: string; csrf_hash: string; created_at: string | Date; absolute_expires_at: string | Date }>("SELECT id, tenant_id, user_id, csrf_hash, created_at, absolute_expires_at FROM brain_web_sessions WHERE session_hash = $1 AND revoked_at IS NULL AND absolute_expires_at > $2 AND idle_expires_at > $2", [hash(sessionId), nowIso]); const row = rows[0]; if (!row || row.tenant_id !== context.tenantId || stateChanging && hash(csrfToken) !== row.csrf_hash) throw new Error("invalid or expired session"); const renewed = await this.store.query<{ idle_expires_at: string | Date; absolute_expires_at: string | Date }>("UPDATE brain_web_sessions SET last_seen_at = $2, idle_expires_at = LEAST($3::timestamptz, absolute_expires_at) WHERE id = $1 AND tenant_id = $4 AND revoked_at IS NULL AND absolute_expires_at > $2 AND idle_expires_at > $2 RETURNING idle_expires_at, absolute_expires_at", [row.id, nowIso, new Date(now.getTime() + 30 * 60_000).toISOString(), context.tenantId]); const refreshed = renewed[0]; if (!refreshed) throw new Error("invalid or expired session"); return { id: sessionId, tenantId: row.tenant_id, userId: row.user_id, csrfToken, createdAt: new Date(row.created_at).toISOString(), idleExpiresAt: new Date(refreshed.idle_expires_at).toISOString(), absoluteExpiresAt: new Date(refreshed.absolute_expires_at).toISOString() }; }
	async revokeWebSession(context: ControlPlaneContext, sessionId: string): Promise<void> { if (!sessionId.trim()) throw new Error("session ID is required"); const rows = await this.store.query<{ id: string }>("UPDATE brain_web_sessions SET revoked_at = now() WHERE session_hash = $1 AND tenant_id = $2 AND revoked_at IS NULL RETURNING id", [hash(sessionId), context.tenantId]); if (!rows.length) throw new Error("session is unavailable"); }
	async consumeQuota(context: ControlPlaneContext, input: { operation: string; units: number; limit: number; windowMs: number }): Promise<{ used: number; remaining: number; resetAt: string }> { if (!context.principal.trim() || !context.tenantId.trim() || !input.operation.trim() || !Number.isInteger(input.units) || input.units < 0 || !Number.isInteger(input.limit) || input.limit < 0 || !Number.isInteger(input.windowMs) || input.windowMs < 1) throw new Error("invalid quota"); const now = this.clock(); const windowStart = new Date(Math.floor(now.getTime() / input.windowMs) * input.windowMs); const rows = await this.store.query<{ units: number }>("INSERT INTO brain_quota_usage (tenant_id, principal_id, brain_id, operation, window_start, units) VALUES ($1, $2, $3, $4, $5, $6) ON CONFLICT (tenant_id, principal_id, brain_id, operation, window_start) DO UPDATE SET units = brain_quota_usage.units + EXCLUDED.units RETURNING units", [context.tenantId, context.principal, context.brainId ?? "local", input.operation, windowStart.toISOString(), input.units]); const used = Number(rows[0]?.units ?? 0); if (used > input.limit) { await this.store.query("UPDATE brain_quota_usage SET units = units - $6 WHERE tenant_id = $1 AND principal_id = $2 AND brain_id = $3 AND operation = $4 AND window_start = $5", [context.tenantId, context.principal, context.brainId ?? "local", input.operation, windowStart.toISOString(), input.units]); throw new Error("quota exceeded"); } return { used, remaining: input.limit - used, resetAt: new Date(windowStart.getTime() + input.windowMs).toISOString() }; }
	async dashboard(context: ControlPlaneContext): Promise<AdminDashboard> { requireAdmin(context); const scalar = async (sql: string): Promise<number> => Number((await this.store.query<{ count: number | string }>(sql, [context.tenantId]))[0]?.count ?? 0); return { tenantId: context.tenantId, brains: await scalar("SELECT count(*) AS count FROM brain_registry WHERE tenant_id = $1"), users: await scalar("SELECT count(*) AS count FROM brain_memberships WHERE tenant_id = $1"), sources: await scalar("SELECT count(*) AS count FROM brain_source_registrations WHERE tenant_id = $1"), activeJobs: await scalar("SELECT count(*) AS count FROM brain_jobs WHERE tenant_id = $1 AND status IN ('pending', 'running')"), failedJobs: await scalar("SELECT count(*) AS count FROM brain_jobs WHERE tenant_id = $1 AND (status = 'failed' OR dead_lettered = true)"), projectionLag: await scalar("SELECT count(*) AS count FROM brain_projection_runs WHERE tenant_id = $1 AND status <> 'complete'"), activeModels: await scalar("SELECT count(*) AS count FROM brain_model_descriptors WHERE tenant_id = $1 AND active = true"), auditEvents: await scalar("SELECT count(*) AS count FROM brain_audit_events WHERE tenant_id = $1") }; }
	async listAudit(context: ControlPlaneContext, limit = 100): Promise<AuditEvent[]> { if (!context.principal.trim() || !context.tenantId.trim()) throw new Error("tenant scope is required"); return (await listAuditEvents(this.store, context.tenantId, limit)).map(redactAdminEvent); }
	async listAuditPage(context: ControlPlaneContext, limit = 100, after?: string): Promise<AuditEventPage> { if (!context.principal.trim() || !context.tenantId.trim()) throw new Error("tenant scope is required"); const page = await listAuditEventsPage(this.store, { tenantId: context.tenantId, limit, after }); return { ...page, events: page.events.map(redactAdminEvent) }; }
	async createAgentRun(context: ControlPlaneContext, input: { id?: string; brainId: string; agent: string; operation: string; baseCommit: string; policy: AutomationPolicy; plannedPaths: string[] }): Promise<DurableAgentRun> { if (!context.principal.trim() || !context.tenantId.trim() || context.scope === "read" || !input.brainId.trim() || !input.agent.trim() || !input.operation.trim() || !input.baseCommit.trim() || !input.plannedPaths.length) throw new Error("invalid agent run intent"); if (input.policy.authority === "admin" && context.scope !== "admin" || !input.policy.dryRun && input.policy.authority === "read") throw new Error("agent authority is insufficient"); const id = input.id ?? randomUUID(); await this.store.query("INSERT INTO brain_agent_runs (id, tenant_id, brain_id, agent, operation, base_commit, authority, budget, planned_paths, status) VALUES ($1, $2, $3, $4, $5, $6, $7, $8::jsonb, $9::jsonb, 'planned')", [id, context.tenantId, input.brainId, input.agent, input.operation, input.baseCommit, input.policy.authority, JSON.stringify(input.policy), JSON.stringify(input.plannedPaths)]); return { id, tenantId: context.tenantId, brainId: input.brainId, agent: input.agent, operation: input.operation, baseCommit: input.baseCommit, authority: input.policy.authority, budget: { ...input.policy }, plannedPaths: [...input.plannedPaths], status: "planned" }; }
	async updateAgentRun(context: ControlPlaneContext, id: string, update: { status: AgentRunStatus; proposal?: MutationProposal; result?: { commit?: string; dryRun: boolean; completedAt: string }; error?: string }): Promise<DurableAgentRun> {
		if (!context.principal.trim() || !context.tenantId.trim() || !id.trim()) throw new Error("invalid agent run update");
		const current = await this.getAgentRun(context, id);
		const transitions: Record<AgentRunStatus, AgentRunStatus[]> = { planned: ["executing", "proposed", "rejected", "failed"], executing: ["proposed", "rejected", "failed"], proposed: ["committed", "rejected", "failed"], committed: [], rejected: [], failed: [] };
		if (!transitions[current.status].includes(update.status)) throw new Error("invalid agent run transition");
		if (update.status === "proposed" && !update.proposal) throw new Error("agent proposal is required");
		if (update.status === "committed" && (!update.result || !current.proposal)) throw new Error("agent commit requires a persisted proposal and result");
		if (update.status === "failed" && !update.error?.trim() || update.status === "rejected" && !update.error?.trim()) throw new Error("agent run failure requires a reason");
		const rows = await this.store.query<{ id: string; tenant_id: string; brain_id: string; agent: string; operation: string; base_commit: string; authority: AutomationPolicy["authority"]; budget: unknown; planned_paths: unknown; status: AgentRunStatus; proposal: unknown; result: unknown; error: string | null }>("UPDATE brain_agent_runs SET status = $3, proposal = $4::jsonb, result = $5::jsonb, error = $6, updated_at = now() WHERE id = $1 AND tenant_id = $2 AND status = $7 RETURNING id, tenant_id, brain_id, agent, operation, base_commit, authority, budget, planned_paths, status, proposal, result, error", [id, context.tenantId, update.status, update.proposal ? JSON.stringify(update.proposal) : current.proposal ? JSON.stringify(current.proposal) : null, update.result ? JSON.stringify(update.result) : current.result ? JSON.stringify(current.result) : null, update.error ?? null, current.status]);
		if (!rows[0]) throw new Error("agent run changed during update");
		return this.toAgentRun(rows[0]);
	}
	async getAgentRun(context: ControlPlaneContext, id: string): Promise<DurableAgentRun> { const rows = await this.store.query<{ id: string; tenant_id: string; brain_id: string; agent: string; operation: string; base_commit: string; authority: AutomationPolicy["authority"]; budget: unknown; planned_paths: unknown; status: AgentRunStatus; proposal: unknown; result: unknown; error: string | null }>("SELECT id, tenant_id, brain_id, agent, operation, base_commit, authority, budget, planned_paths, status, proposal, result, error FROM brain_agent_runs WHERE id = $1 AND tenant_id = $2", [id, context.tenantId]); if (!rows[0]) throw new Error("agent run is unavailable"); return this.toAgentRun(rows[0]); }
	async listRecoverableAgentRuns(context: ControlPlaneContext): Promise<DurableAgentRun[]> { if (!context.principal.trim() || !context.tenantId.trim()) throw new Error("agent recovery scope is required"); const rows = await this.store.query<{ id: string; tenant_id: string; brain_id: string; agent: string; operation: string; base_commit: string; authority: AutomationPolicy["authority"]; budget: unknown; planned_paths: unknown; status: AgentRunStatus; proposal: unknown; result: unknown; error: string | null }>("SELECT id, tenant_id, brain_id, agent, operation, base_commit, authority, budget, planned_paths, status, proposal, result, error FROM brain_agent_runs WHERE tenant_id = $1 AND status IN ('planned', 'executing', 'proposed') ORDER BY created_at, id", [context.tenantId]); return rows.map((row) => this.toAgentRun(row)); }
	private toAgentRun(row: { id: string; tenant_id: string; brain_id: string; agent: string; operation: string; base_commit: string; authority: AutomationPolicy["authority"]; budget: unknown; planned_paths: unknown; status: AgentRunStatus; proposal: unknown; result: unknown; error: string | null }): DurableAgentRun { return { id: row.id, tenantId: row.tenant_id, brainId: row.brain_id, agent: row.agent, operation: row.operation, baseCommit: row.base_commit, authority: row.authority, budget: jsonValue(row.budget, {} as AutomationPolicy), plannedPaths: jsonValue(row.planned_paths, [] as string[]), status: row.status, ...(row.proposal ? { proposal: jsonValue(row.proposal, {} as MutationProposal) } : {}), ...(row.result ? { result: jsonValue(row.result, {} as DurableAgentRun["result"]) } : {}), ...(row.error ? { error: row.error } : {}) }; }
	async recordRollback(context: ControlPlaneContext, input: { brainId: string; runId?: string; targetKind: string; targetId: string; rollbackRef: string; metadata?: Record<string, unknown> }): Promise<RollbackReceipt> { if (!context.principal.trim() || !context.tenantId.trim() || !input.brainId.trim() || !input.targetKind.trim() || !input.targetId.trim() || !input.rollbackRef.trim()) throw new Error("invalid rollback receipt"); const rows = await this.store.query<{ id: string; created_at: string | Date }>("INSERT INTO brain_rollback_receipts (id, tenant_id, brain_id, run_id, target_kind, target_id, rollback_ref, metadata) VALUES ($1, $2, $3, $4, $5, $6, $7, $8::jsonb) RETURNING id, created_at", [randomUUID(), context.tenantId, input.brainId, input.runId ?? null, input.targetKind, input.targetId, input.rollbackRef, JSON.stringify(input.metadata ?? {})]); return { id: rows[0]!.id, tenantId: context.tenantId, brainId: input.brainId, ...(input.runId ? { runId: input.runId } : {}), targetKind: input.targetKind, targetId: input.targetId, rollbackRef: input.rollbackRef, metadata: input.metadata ?? {}, createdAt: new Date(rows[0]!.created_at).toISOString() }; }
	async recordMigrationDrill(context: ControlPlaneContext, input: { brainId: string; stage: string; status?: MigrationDrill["status"]; evidence?: Record<string, unknown> }): Promise<MigrationDrill> { requireAdmin(context); if (!input.brainId.trim() || !input.stage.trim()) throw new Error("invalid migration drill"); const status = input.status ?? "planned"; const rows = await this.store.query<{ id: string; created_at: string | Date }>("INSERT INTO brain_migration_drills (id, tenant_id, brain_id, stage, status, evidence, completed_at) VALUES ($1, $2, $3, $4, $5, $6::jsonb, CASE WHEN $5 IN ('passed', 'failed') THEN now() ELSE NULL END) RETURNING id, created_at", [randomUUID(), context.tenantId, input.brainId, input.stage, status, JSON.stringify(input.evidence ?? {})]); await this.audit(context, "admin.migration-drill.recorded", rows[0]!.id, { brainId: input.brainId, stage: input.stage, status }); return { id: rows[0]!.id, tenantId: context.tenantId, brainId: input.brainId, stage: input.stage, status, evidence: input.evidence ?? {}, createdAt: new Date(rows[0]!.created_at).toISOString() }; }
	async planSchemaUpgrade(context: ControlPlaneContext, input: { brainId: string; fromVersion: string; toVersion: string; changes: SchemaUpgradePlan["changes"] }): Promise<SchemaUpgradePlan> { requireAdmin(context); if (!input.brainId.trim() || !input.fromVersion.trim() || !input.toVersion.trim() || !input.changes.length || input.changes.some((change) => !change.path.trim() || !change.to.trim())) throw new Error("invalid schema upgrade plan"); const id = randomUUID(); await this.store.query("INSERT INTO brain_schema_upgrade_plans (id, tenant_id, brain_id, from_version, to_version, status, changes) VALUES ($1, $2, $3, $4, $5, 'planned', $6::jsonb)", [id, context.tenantId, input.brainId, input.fromVersion, input.toVersion, JSON.stringify(input.changes)]); return { id, tenantId: context.tenantId, brainId: input.brainId, fromVersion: input.fromVersion, toVersion: input.toVersion, status: "planned", changes: [...input.changes] }; }
	async approveSchemaUpgrade(context: ControlPlaneContext, id: string): Promise<SchemaUpgradePlan> { requireAdmin(context); const rows = await this.store.query<{ id: string; tenant_id: string; brain_id: string; from_version: string; to_version: string; status: SchemaUpgradePlan["status"]; changes: unknown; approval: unknown }>("UPDATE brain_schema_upgrade_plans SET status = 'approved', approval = $3::jsonb, updated_at = now() WHERE id = $1 AND tenant_id = $2 AND status = 'planned' RETURNING id, tenant_id, brain_id, from_version, to_version, status, changes, approval", [id, context.tenantId, JSON.stringify({ principal: context.principal, at: this.clock().toISOString() })]); if (!rows[0]) throw new Error("schema upgrade plan is unavailable"); const row = rows[0]; return { id: row.id, tenantId: row.tenant_id, brainId: row.brain_id, fromVersion: row.from_version, toVersion: row.to_version, status: row.status, changes: jsonValue(row.changes, []), approval: jsonValue(row.approval, undefined) }; }
	async setSchemaUpgradeStatus(context: ControlPlaneContext, id: string, status: "applied" | "rolled_back" | "rejected"): Promise<void> { requireAdmin(context); const rows = await this.store.query<{ id: string }>("UPDATE brain_schema_upgrade_plans SET status = $3, updated_at = now() WHERE id = $1 AND tenant_id = $2 AND status IN ('approved', 'applied') RETURNING id", [id, context.tenantId, status]); if (!rows.length) throw new Error("schema upgrade plan cannot change state"); }
}

export function redactAdminEvent(event: AuditEvent): AuditEvent { const metadata = Object.fromEntries(Object.entries(event.metadata).filter(([key, value]) => (!/(content|token|secret|cookie|prompt|body|text)/iu.test(key) && typeof value !== "string") || key === "occurredAt")); return { ...event, metadata }; }
